# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Count of Krigsvold
email: info@basuhoward.org
description: >- # this means to ignore newlines until "baseurl:"
  Our website is dedicated to providing comprehensive information about
  Antarctica, covering topics such as its unique ecosystems, scientific
  research, environmental conservation efforts, and the role of the
  continent in global climate regulation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krigsvold.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: basuhoward

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

# Build settings
plugins:
  - jekyll-feed
  - jekyll-algolia

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

algolia:
  application_id:       F2YSZQ2KZ4
  index_name:           krigsvold-search
  search_only_api_key:  2d8dc045127e744060be5e0aa0b74db7
